# Generated by Django 3.2.2 on 2021-05-12 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='INN')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance')),
                ('status', models.CharField(choices=[('public', 'Activate')], default='public', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
