# Generated by Django 3.2.2 on 2021-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'User Info'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.CharField(choices=[('active', 'Activate')], default='active', max_length=6),
        ),
    ]
