# Generated by Django 3.2.2 on 2021-05-12 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_userinfo_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='Account',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'User accounts'},
        ),
    ]
